### ISSUE TITLE
Package for NPM

### ISSUE THREAD

**Issue by pauleustice** [Pathsofdesign/postcss-fakeid#2]
I'm using Grunt to run my postcss task and was hoping to integrate fakeid into that process, but I noticed it's not on NPM. Any chance of you putting it out there?

Cheers!

**Comment by andrewdelprete** [comment]
@pauleustice that's definitely a possibility! I'll see if I can get some time to do this.

**Comment by peterramsing** [comment]
@Pathsofdesign I'd buy pitch in a high-five if you got this on npm. :+1:

**Comment by andrewdelprete** [comment]
This is now added to NPM. :rocket:

**Comment by pauleustice** [comment]
Works great with Grunt - thanks! :)
