### ISSUE TITLE
Not transforming ids 

### ISSUE THREAD

**Issue by json-uk** [Pathsofdesign/postcss-fakeid#3]
I'm trying to use this in my gulp file as part of a postcss task and this plugin runs;  but doesn't transform the (only) selector with and id. 

``` css
#something {
  color: purple;
}
```

**My gulpfile includes this task:**

``` js
gulp.task ('css', function (){
  processors = [
    p.cssnext({
        sourcemap: true,
        compress: false,
        autoprefixer: false  
    }),
    p.fakeid()
  ];
  return gulp.src('src/css/*.css')
    .pipe(plugins.plumber())
    .pipe(plugins.postcss(processors))
    .pipe(gulp.dest('dist/css/'));
});
```

I am also using the `postcss-load-plugins` and `gulp-load-plugins` to handle auto-loading for me and keep my gulpfile small.

Any ideas why this wouldn't be working?

**Comment by andrewdelprete** [comment]
Man to be honest, I haven't used the *-load-plugins module before. I really like what it does but I never got around to it. I've added `postcss-fakeid` to NPM. Perhaps if you install it via NPM your loaders will work.

**Comment by json-uk** [comment]
@pathsofdesign just updated and same... I did try without -load-plugins and the same result; no transformation.

I'll poke around but I'm not seeing anything in the code that's amiss

Thanks!

**Comment by andrewdelprete** [comment]
Interesting! let me know what you come up with. It appears to be working for me via gulp. You fun you could checkout the repo, npm install, and add a `src/css/app.css` file with a selector # ID in it. Then run `gulp` from there. It must be something to do with the way the plugin is being called maybe?

**Comment by peterramsing** [comment]
I'm not sure if this is user error, but I'm having issues with it not compiling out as well.

```
var gulp         = require('gulp'),
    postcss      = require('gulp-postcss'),
    sourcemaps   = require('gulp-sourcemaps'),
    autoprefixer = require('gulp-autoprefixer'),
    lost         = require('lost'),
    uglify       = require('gulp-uglify'),
    plumber      = require('gulp-plumber'),
    stylus       = require('gulp-stylus'),
    concat       = require('gulp-concat'),
    browserSync  = require('browser-sync').create(),
    minifyCss    = require('gulp-minify-css'),
    fakeId         = require('postcss-fakeid'),
    rupture      = require('rupture');

...

gulp.task('styles', function() {
    var options = {
        use: [ rupture() ]
    };

    return gulp.src('src/css/main.styl')
        .pipe(plumber({
        errorHandler: errHandler
    }))
    .pipe(sourcemaps.init())
    .pipe(stylus(options))
    .pipe(postcss([
        fakeId(),
        lost()
    ]))
    .pipe(autoprefixer())
    .pipe(minifyCss())
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('dist/css/'))
    .pipe(browserSync.reload({ stream: true }));;
});

...

```

Lost is compiling just fine and there are no errors being thrown. I've tried several variations and can't seem to figure out what's up.

User error?

**Comment by json-uk** [comment]
Was there an update of gulp recently? I'm confused too as all the tests work in the fakeid repo...

**Comment by andrewdelprete** [comment]
@peterramsing within your postcss() method you need to reference the plugin rather than calling it.

postcss([ fakeId ]) not postcss([ fakeId() ])

**Comment by json-uk** [comment]
I did just that and still not running. I even required it manually just to be sure

**Comment by peterramsing** [comment]
@Pathsofdesign So we played around with it some more and got it to work great on your test snippet: 

```
#foo .bar {
    font-size: 1rem;
}
```

I then copied our raw .css before it got minified and tried to run fakeid on it and it didn't compile. [Here's](https://gist.github.com/peterramsing/0bd973da7cc18f38a572) the css we're working with. Could it be that our css is not allowing it to compile?

https://gist.github.com/peterramsing/0bd973da7cc18f38a572

**Comment by andrewdelprete** [comment]
@peterramsing The GIST isn't coming up for me

**Comment by peterramsing** [comment]
Try now? https://gist.github.com/peterramsing/0bd973da7cc18f38a572

(sorry-had the clone link, not actual link...)

**Comment by andrewdelprete** [comment]
Ah ha! It looks like there is definitely a bug. When I try something like this it breaks. If there are any classes or elements defined before the #id then it doesn't convert it to an attribute. I'll have to take a look and what I did wrong here. It's possible I broke it on a refactor at some point.

```
.class { color: red }
#id { color: blue }
```

**Comment by andrewdelprete** [comment]
Okay I fixed it, I'll be pushing it up shortly. Thanks for all your feedback guys.

**Comment by peterramsing** [comment]
Thanks for snagging it! Anything else you need tested or help with? We're looking to implement this in our latest build workflow so let me know if you need any help.

**Comment by json-uk** [comment]
Thanks for fixing the issue!

I'd recommend using more rules in your test to ensure your code works under a more realistic scenarios.

**Comment by andrewdelprete** [comment]
I've pushed the change up and updated NPM. I also added two more tests but could use quite a bit more if you guys are interested. Let me know if it works for you guys!

**Comment by peterramsing** [comment]
works great! Thanks!
